### ISSUE TITLE
Install instructions would be useful

### ISSUE THREAD

**Issue by cbird808** [OnofriAndreaPG/aomisc#1]
Hi Andrea,

Thank you for posting your great page on non linear line fitting https://www.statforbiology.com/nonlinearregression/usefulequations#power_curve  !

I, however, couldn’t install aomisc through cran

```R
> install.packages("aomisc")
Installing package into ‘C:/Users/cbird/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘aomisc’ is not available (for R version 3.6.3)
```

But I was successful using the following  

```R
library(devtools)
install_github("DeveloperName/PackageName")
```

It would probably be useful to others to add something about installation to the README and on your web pages.

Cheers,

Chris

**Comment by OnofriAndreaPG** [comment]
Thanks for this suggestion! I updated the README file.
