### ISSUE TITLE
Not working in R 4.0.3 

### ISSUE THREAD

**Issue by plantgustaf** [OnofriAndreaPG/aomisc#3]
I just came across this rather useful package, but it doesn't seem to work with 4.0.3 (2020-10-10).
Best,
Gustaf

**Comment by mattmar** [comment]
Hey, I had the same problem in 4.0.3 and solved installing:
install.packages("drc")
install.packages("cpp11")

and then:
devtools::install_github("onofriAndreaPG/aomisc")
