### ISSUE TITLE
Release on CRAN?

### ISSUE THREAD

**Issue by slhck** [OnofriAndreaPG/aomisc#6]
This package looks super useful. Would you consider releasing it on CRAN?

**Comment by OnofriAndreaPG** [comment]
Hello and thanks for your comment. This package was mainly meant as a teaching aid, but I decided to share it, just in case it might be useful. I have the idea of making a new package with a better name (drctool or similar) and share it to CRAN... but, ... time is lacking... sorry ...

**Comment by OnofriAndreaPG** [comment]
The content of the aomisc package has been moved to the new statforbiology package, that is available both on CRAN and as a github repository
