### ISSUE TITLE
I cannot install aomisc 

### ISSUE THREAD

**Issue by marioxis** [OnofriAndreaPG/aomisc#7]
Hi, 
II want to do the power curve regression and I can't install the aomisc package from this command:
 install.packages("remotes")
remotes::install_github("OnofriAndreaPG/aomisc") 
or 
devtools::install_github("onofriAndreaPG/aomisc")

**My issue:** 

* installing *source* package 'aomisc' ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'drc' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace 'ellipsis' 0.3.1 is being loaded, but >= 0.3.2 is required
Erro: package 'drc' could not be loaded
Além disso: Warning message:
package 'drc' was built under R version 4.0.5 
Execução interrompida
ERROR: lazy loading failed for package 'aomisc'
* removing 'C:/Users/mario/OneDrive/Documentos/R/win-library/4.0/aomisc'

**Comment by OnofriAndreaPG** [comment]
The content of the aomisc package has been moved to the new statforbiology package, that is available both on CRAN and as a github repository
