### ISSUE TITLE
something is broken, R 4.1.1

### ISSUE THREAD

**Issue by jakeberv** [OnofriAndreaPG/aomisc#8]
Running 4.1.1 on MacOS Mojave --

Looks like something is broken. I tried following the advice here https://github.com/OnofriAndreaPG/aomisc/issues/3 
but I'm still getting this error when trying to fit an asymptotic model -- 

`> model <- nls(Y ~ NLS.asymReg(X, init, m, plateau) )
Error in (attr(object, "initial"))(mCall = mCall, data = data, LHS = LHS,  : 
  unused arguments (control = list(50, 1e-05, 0.0009765625, FALSE, FALSE, 0, FALSE), trace = FALSE)`

Any idea what might be going on?

Thanks,
Jacob Berv

**Comment by OnofriAndreaPG** [comment]
This was solved. However, the content of the aomisc package has been moved to the new statforbiology package, that is available both on CRAN and as a github repository
